config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  resources :responsavels
  get 'home/index'
  resources :alunos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/aluno.rb
class Aluno < ApplicationRecord
    # responsaveis = responsavels #
    has_many :responsavels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/responsavel.rb
class Responsavel < ApplicationRecord
  belongs_to :aluno
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: %i[ show edit update destroy ]

  # GET /alunos or /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1 or /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos or /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to aluno_url(@aluno), notice: "Aluno was successfully created." }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1 or /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to aluno_url(@aluno), notice: "Aluno was successfully updated." }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1 or /alunos/1.json
  def destroy
    @aluno.destroy

    respond_to do |format|
      format.html { redirect_to alunos_url, notice: "Aluno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aluno_params
      params.require(:aluno).permit(:nome, :serie, :turno, :ra)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/responsavels_controller.rb
class ResponsavelsController < ApplicationController
  before_action :set_responsavel, only: %i[ show edit update destroy ]

  # GET /responsavels or /responsavels.json
  def index
    @responsavels = Responsavel.all
  end

  # GET /responsavels/1 or /responsavels/1.json
  def show
  end

  # GET /responsavels/new
  def new
    @responsavel = Responsavel.new
  end

  # GET /responsavels/1/edit
  def edit
  end

  # POST /responsavels or /responsavels.json
  def create
    @responsavel = Responsavel.new(responsavel_params)

    respond_to do |format|
      if @responsavel.save
        format.html { redirect_to responsavel_url(@responsavel), notice: "Responsavel was successfully created." }
        format.json { render :show, status: :created, location: @responsavel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @responsavel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsavels/1 or /responsavels/1.json
  def update
    respond_to do |format|
      if @responsavel.update(responsavel_params)
        format.html { redirect_to responsavel_url(@responsavel), notice: "Responsavel was successfully updated." }
        format.json { render :show, status: :ok, location: @responsavel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @responsavel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsavels/1 or /responsavels/1.json
  def destroy
    @responsavel.destroy

    respond_to do |format|
      format.html { redirect_to responsavels_url, notice: "Responsavel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsavel
      @responsavel = Responsavel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def responsavel_params
      params.require(:responsavel).permit(:aluno_id, :nome, :cpf, :contato, :status)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/responsavels_helper.rb
module ResponsavelsHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/alunos/_aluno.html.erb
<div id="<%= dom_id aluno %>">
  <p>
    <strong>Nome:</strong>
    <%= aluno.nome %>
  </p>

  <p>
    <strong>Serie:</strong>
    <%= aluno.serie %>
  </p>

  <p>
    <strong>Turno:</strong>
    <%= aluno.turno %>
  </p>

  <p>
    <strong>Ra:</strong>
    <%= aluno.ra %>
  </p>

</div>

app/views/alunos/_form.html.erb
<%= form_with(model: aluno) do |form| %>
  <% if aluno.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
        <% aluno.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
        <div class="navbar-bottom pace-done pace-done">
         <div class="row justify-content-center">
    
            <div class="row ">
                <div class="col-md-4">
                  <div class="fieldlabels">
                    <label>Nome Completo <abbr title="obrigatório">*</abbr></label>
                    <%= form.text_field :nome, autocomplete: "nope" , maxlength: "50" ,class: 'form-control', placeholder: 'Ex: João Souza Cardoso', required: true%>
                  </div>
                </div>

                <div class="col-md-4">
                  <div class="fieldlabels">
                    <label>Turno <abbr title="obrigatório">*</abbr></label>
                    <%= form.text_field :turno, class: 'form-control' , id: 'cpf' , placeholder: 'selecione', required: true%>
                  </div>
                </div>

                <div class="col-md-4">
                  <div class="fieldlabels">
                    <label>RESGISTRO ACADEMICO <abbr title="obrigatório">*</abbr></label>
                    <%= form.text_field :ra, maxlength: "15" , class: 'form-control' , id:'rg',placeholder: 'Ex: 4001543', required: true%>
                  </div>
                </div>

                <div class="col-md-4">
                  <div class="fieldlabels">
                    <label>SERIE <abbr title="obrigatório">*</abbr></label>
                    <%= form.text_field :serie, class: 'form-control', required: true%>
                  </div>
                </div>
              </div>
              






             <div class="form-actions float-right" >
                <%= form.submit 'Enviar', class:"btn btn-primary", data: { confirm: "Tem certeza que deseja enviar suas informações agora?" } %>
              </div>

<% end %>
 </div>
              </div>

app/views/alunos/edit.html.erb
<h1>Editing aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Show this aluno", @aluno %> |
  <%= link_to "Back to alunos", alunos_path %>
</div>

app/views/alunos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Alunos</h1>

<div id="alunos">
  <% @alunos.each do |aluno| %>
    <%= render aluno %>
    <p>
      <%= link_to "Show this aluno", aluno %>
    </p>
  <% end %>
</div>

<%= link_to "New aluno", new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New aluno</h1>

<%= render "form", aluno: @aluno %>

<br>

<div>
  <%= link_to "Back to alunos", alunos_path %>
</div>

app/views/alunos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aluno %>

<div>
  <%= link_to "Edit this aluno", edit_aluno_path(@aluno) %> |
  <%= link_to "Back to alunos", alunos_path %>

  <%= button_to "Destroy this aluno", @aluno, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="card" style=" border: none;">
<span style="font-size: 100px; padding: 300px">PASS <br> CARD <br> KIDS</span>
</div>
<h1><img src="https://colegiosapiens.com/wp-content/uploads/2022/05/menino-colegio-sapiens2.png"  height="alto" style="position: relative;    left: 935px;
    margin-top: -1160px;
}"></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PassCardKids</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"  integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"> <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: blueviolet!important;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" >
    <img src="https://gruposapiens.com.br/img/logo-colegio-negativa.png" width="200" height="alto" style="position: relative;left: 60px;">
    </a>
   
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav me-auto mb-4 mb-lg-0" style="position: relative;left: 140px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="home/index" style="font-weight: 700;
                              font-style: normal;
                              color: rgb(255, 255, 255);
                              text-decoration: none;" >Home</a>
        </li>
        <li class="nav-item" style="position: relative;left: 150px;">
          <a class="nav-link" href="#" style="font-weight: 700;
                              font-style: normal;
                              color: rgb(255, 255, 255);
                              text-decoration: none;">Área do administrador</a>
        </li>
        <li class="nav-item" style="position: relative;left: 300px;">
          <a class="nav-link" href="#" style="font-weight: 700;
                              font-style: normal;
                              color: rgb(255, 255, 255);
                              text-decoration: none;">Área do Responsável </a>
        </li>
      <li class="nav-item" style="position: relative;left: 450px;">
          <a class="nav-link" href="#" style="font-weight: 700;
                              font-style: normal;
                              color: rgb(255, 255, 255);
                              text-decoration: none;">Fale Conosco </a>
        </li>

      </ul>


    
    </div>
  </div>
</nav>
    <%= yield %>
  </body>


  <!--- Footer --->
  <footer class=" text-center text-white" id="rodape">
  <!-- Grid container -->
 
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 text-dark" >
    © 2023 - Colégio e Curso Sapiens -
    <a class="text-dark" > Todos os direitos reservados </a>
  </div>
  <!-- Copyright -->
</footer>
  <!--# Footer #-->


</html>

app/views/responsavels/_form.html.erb
<%= form_with(model: responsavel) do |form| %>
  <% if responsavel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(responsavel.errors.count, "error") %> prohibited this responsavel from being saved:</h2>

      <ul>
        <% responsavel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :aluno_id, style: "display: block" %>
    <%= form.text_field :aluno_id %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :contato, style: "display: block" %>
    <%= form.text_field :contato %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/responsavels/_responsavel.html.erb
<div id="<%= dom_id responsavel %>">
  <p>
    <strong>Aluno:</strong>
    <%= responsavel.aluno_id %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= responsavel.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= responsavel.cpf %>
  </p>

  <p>
    <strong>Contato:</strong>
    <%= responsavel.contato %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= responsavel.status %>
  </p>

</div>

app/views/responsavels/edit.html.erb
<h1>Editing responsavel</h1>

<%= render "form", responsavel: @responsavel %>

<br>

<div>
  <%= link_to "Show this responsavel", @responsavel %> |
  <%= link_to "Back to responsavels", responsavels_path %>
</div>

app/views/responsavels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Responsavels</h1>

<div id="responsavels">
  <% @responsavels.each do |responsavel| %>
    <%= render responsavel %>
    <p>
      <%= link_to "Show this responsavel", responsavel %>
    </p>
  <% end %>
</div>

<%= link_to "New responsavel", new_responsavel_path %>

app/views/responsavels/new.html.erb
<h1>New responsavel</h1>

<%= render "form", responsavel: @responsavel %>

<br>

<div>
  <%= link_to "Back to responsavels", responsavels_path %>
</div>

app/views/responsavels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @responsavel %>

<div>
  <%= link_to "Edit this responsavel", edit_responsavel_path(@responsavel) %> |
  <%= link_to "Back to responsavels", responsavels_path %>

  <%= button_to "Destroy this responsavel", @responsavel, method: :delete %>
</div>